  db:
    image: mysql/mysql-server:8.0
    container_name: db
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_520_ci
    environment:  # .env 파일의 환경 변수를 로드
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=wishtree
    ports:
      - '3306:3306'
    volumes:
      - db_vol:/var/lib/mysql

volumes:
  db_vol:
    driver: local